### PR TITLE
Merge translation strings to single file

### PR DESCRIPTION
**Pull request by JulianGro**
This merges translation strings into single files, so we can use just a single component in Weblate. This is needed to keep Weblate somewhat tidy when using the Weblate instance provided by Weblate for FLOSS projects.

You can see it working here:
https://hosted.weblate.org/projects/overte/overte-documentation-test/
Keep in mind that the total number of strings is now a bit lower since there were some duplicates across the different files.

When it comes to reviews, the translation files are pretty much always automatically edited and don't require review.
Any copyright or anything that might be wrong will be fixed by Weblate once it is fully set up.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
I noticed that .po files have placeholders in author fields:
`# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.`

**Comment by JulianGro** [comment]
Yes, I have been letting Weblate take care of all metadata.
I guess I will update the PR, since this metadata is autogenerated by Sphinx and it never got changed.

**Comment by ksuprynowicz** [comment]
It seems like the automatic build is failing with such warning:
` /home/runner/work/overte-docs-sphinx/overte-docs-sphinx/docs/source/index.rst: WARNING: document isn't included in any toctree`
And lots of warnings about reference target not being found:
`/home/runner/work/overte-docs-sphinx/overte-docs-sphinx/docs/source/create/avatars/avatar-standards.md:11: WARNING: 'myst' reference target not found: #glossary`

**Comment by JulianGro** [comment]
Those are unrelated to the translation.

That first warning is only that; We cannot do it any other way until ReadTheDocs upgrades their system (which I was told will happen in a couple of weeks):

The other warnings I don't know where they are suddenly coming from, but again they are unrelated to the translation.

EDIT: https://github.com/overte-org/overte-docs-sphinx/issues/4

**Pull request merged**
